/*
 * generated by Xtext
 */
package ru.nsu.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DbDslUiModule extends ru.nsu.xtext.ui.AbstractDbDslUiModule {
	public DbDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
