/*
 * generated by Xtext
 */
package ru.nsu.xtext.validation

import org.eclipse.xtext.validation.Check
import ru.nsu.xtext.dbDsl.ForeignKeyDecl
import ru.nsu.xtext.dbDsl.DbDslPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DbDslValidator extends AbstractDbDslValidator {

  public static val TYPE_ERROR_FOR_FK_Decl = 'typeErrorForFKDecl'

	@Check
	def checkFKDeclMustHaveSameType(ForeignKeyDecl fkDecl) {
		if (fkDecl.fk.type!=fkDecl.referredcol.type) {
			error('''Foreign key '«fkDecl.fk.name»' has type '«fkDecl.fk.type»' but referred column '«fkDecl.referredcol.name»' has type '«fkDecl.referredcol.type»' ''', 
					DbDslPackage.Literals.FOREIGN_KEY_DECL__FK,
					TYPE_ERROR_FOR_FK_Decl)
		}
	}
}
