/*
 * generated by Xtext
 */
package ru.nsu.xtext.exp1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Exp1DslUiModule extends ru.nsu.xtext.exp1.ui.AbstractExp1DslUiModule {
	public Exp1DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
