/*
 * generated by Xtext
 */
package ru.nsu.xtext;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import com.google.inject.Binder;
import com.google.inject.name.Names;

import ru.nsu.xtext.scoping.DbDslImportedNamespaceAwareLocalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class DbDslRuntimeModule extends ru.nsu.xtext.AbstractDbDslRuntimeModule {

	// make lib-objects available without 'import'
	@Override
	public void configureIScopeProviderDelegate(Binder binder){
	binder.bind(IScopeProvider.class)
	.annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
	.to(DbDslImportedNamespaceAwareLocalScopeProvider.class);
	}
}
