/*
 * generated by Xtext
 */
package ru.nsu.xtext.ui.contentassist

import ru.nsu.xtext.ui.contentassist.AbstractDbDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DbDslProposalProvider extends AbstractDbDslProposalProvider {
}
