/*
 * generated by Xtext
 */
package ru.nsu.xtext.exp1;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Exp1DslStandaloneSetup extends Exp1DslStandaloneSetupGenerated{

	public static void doSetup() {
		new Exp1DslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

