/*
 * generated by Xtext
 */
package ru.nsu.xtext.exp1;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Exp1DslRuntimeModule extends ru.nsu.xtext.exp1.AbstractExp1DslRuntimeModule {

}
