/*
 * generated by Xtext
 */
package ru.nsu.xtext.exp1.ui.contentassist

import ru.nsu.xtext.exp1.ui.contentassist.AbstractExp1DslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Exp1DslProposalProvider extends AbstractExp1DslProposalProvider {
}
